server:
  port: 8081

spring:
  application:
    name: user
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongouser
      password: mongopass    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs      

service:
  base:
    uri: /api/v1
  eureka-username: u
  eureka-password: p
  eureka-server: localhost    
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://${service.eureka-username}:${service.eureka-password}@${service.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5    

system.password: system
